POST https://www.karriemariebaxley.com/api/revalidate-all
content-type: application/json
secret: testing123

{
    "_type": "navigation",
    "slug": "about",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}